### ISSUE TITLE
Clear Server Data?

### ISSUE THREAD

**Issue by henkall** [tfonfara/RemoteForTautulli-Issues#3]
### Description

I have had this fine app on my phone for some time but I have recently change ip on my Tautulli Server but the app does not see that the ip is change and I can not get rid of the old server in the app. I can also not get to the step to add a new server.

I have tried to delete the app from my phone but when i install it again it keeps showing my the old servers ip. It does now let me pick a new server.

### Steps to Reproduce

1. Go to Settings in the app

2. Connect to a different server
3. I can't delete the existing server and I can not add a new one.

**Expected behavior:** 
I would be able to delete the old server and add a new.

**Actual behavior:** 

I shows me the old servers IP

**Reproduces how often:**
All the time.

### Environment

* Device: Iphone 5
* OS version: IOS 10
* App version: 1.3.0.147
* Tautulli version: 2.1.14

![20180629_123042000_ios](https://user-images.githubusercontent.com/1741035/42092632-d7ae6438-7ba9-11e8-8a92-3c486b1520d1.png)

**Comment by tfonfara** [comment]
Adding new servers is currently only supported in pro version. But I'm with you that this a valid scenario, so I'll fix that in next version.

**Comment by henkall** [comment]
Thanks. 👍

**Comment by tfonfara** [comment]
Fixed with v1.3.1.
