### ISSUE TITLE
ETA Time not updated

### ISSUE THREAD

**Issue by panzanni95** [tfonfara/RemoteForTautulli-Issues#4]
### New Issue Checklist

- [x] My issue is related to the [Remote for Tautulli](https://itunes.apple.com/app/id1343177312) app, report issues for Tautulli [here](https://github.com/Tautulli/Tautulli-Issues/issues)
- [x] I updated Remote for Tautulli to the latest version
- [x] I searched for [existing GitHub issues](https://github.com/tfonfara/RemoteForTautulli-Issues/issues)

### Description

ETA Time is not updated every time you tap on a stream to get the details. The first ETA time stay even later

### Steps to Reproduce

1. Tap on a stream 
2. Tap back
3. Tap on the same stream again. Time is updated but not ETA

**Expected behavior:** update ETA

**Actual behavior:** ETA always stays the same

**Reproduces how often:** 100%

### Environment

* Device: iPhone SE
* OS version: 12b8
* App version: 1.5.0
* Tautulli version: 2.1.18

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by tfonfara** [comment]
I'm not sure if I get the issue. ETA is the time when it's expected that the stream ends. ETA is not meant to change at all unless you pause the stream.

**Comment by panzanni95** [comment]
Ah ok nevermind ! I thought it was the time remaining and not the ETA hours and minutes
